/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(255),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

ALTER TABLE animals ADD COLUMN species VARCHAR(255);
ALTER TABLE animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE owners(
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255),
    age INT
);

CREATE TABLE species(
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);



ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD COLUMN species_id INT,
ADD CONSTRAINT fk_species
    FOREIGN KEY (species_id)
    REFERENCES species(id);

ALTER TABLE animals
ADD COLUMN owner_id INT,
ADD CONSTRAINT fk_owner
    FOREIGN KEY (owner_id)
    REFERENCES owners(id);


CREATE TABLE vets(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    age INT,
    date_of_graduation DATE
);

ALTER TABLE vets
ADD CONSTRAINT PK_vets_id PRIMARY KEY (id);

CREATE TABLE specializations (
    species_id INT,
    vet_id INT,
    FOREIGN KEY (species_id) REFERENCES species(id),
    FOREIGN KEY (vet_id) REFERENCES vets(id),
    PRIMARY KEY (species_id, vet_id)
);

CREATE TABLE visits(
    animals_id INT,
    vet_id INT,
    FOREIGN KEY (animals_id) REFERENCES animals(id),
    FOREIGN KEY (vet_id) REFERENCES vets(id),
    PRIMARY KEY (animals_id, vet_id)
);

ALTER TABLE visits
ADD COLUMN date_of_visit DATE;

ALTER TABLE visits
DROP CONSTRAINT visits_pkey;

ALTER TABLE visits
ADD CONSTRAINT visits_key PRIMARY KEY(animals_id,vet_id,date_of_visit);



